
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Dec 26 16:40:06 IST 2013
//----------------------------------------------------

package adtl;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 22;
  public static final int LCBR = 12;
  public static final int LTE = 23;
  public static final int REV = 2;
  public static final int UMINUS = 38;
  public static final int SEMI = 13;
  public static final int INT = 41;
  public static final int MINUS = 24;
  public static final int ASSERT = 3;
  public static final int BAR = 25;
  public static final int NOT = 26;
  public static final int LT = 14;
  public static final int CHOOSE = 4;
  public static final int IN = 5;
  public static final int LP = 15;
  public static final int COMMA = 16;
  public static final int LOCK = 6;
  public static final int RP = 17;
  public static final int PLUS = 27;
  public static final int QUOTE = 40;
  public static final int ASSIGN = 28;
  public static final int IF = 7;
  public static final int ID = 39;
  public static final int DOT = 18;
  public static final int EOF = 0;
  public static final int RCBR = 19;
  public static final int LAND = 29;
  public static final int RETURN = 8;
  public static final int NEW = 9;
  public static final int error = 1;
  public static final int ASSIGN_PLUS = 30;
  public static final int LOR = 31;
  public static final int NEQ = 32;
  public static final int ASSIGN_MINUS = 33;
  public static final int EQ = 34;
  public static final int GTE = 35;
  public static final int TIMES = 36;
  public static final int COLON = 20;
  public static final int ELSE = 10;
  public static final int AT = 21;
  public static final int GT = 37;
  public static final int SET = 11;
}

