from compiler import *
# compile_scheme_file("input.scm","output.asm")

compile_scheme_file("../debugger/scheme code to test compiler/test1.scm","test1.asm")
print("test 1 done")
compile_scheme_file("../debugger/scheme code to test compiler/test2.scm","test2.asm")
print("test 2 done")
compile_scheme_file("../debugger/scheme code to test compiler/test3.scm","test3.asm")
print("test 3 done")
compile_scheme_file("../debugger/scheme code to test compiler/test4.scm","test4.asm")
print("test 4 done")
compile_scheme_file("../debugger/scheme code to test compiler/test5.scm","test5.asm")
print("test 5 done")
compile_scheme_file("../debugger/scheme code to test compiler/test6.scm","test6.asm")
print("test 6 done")
compile_scheme_file("../debugger/scheme code to test compiler/test7.scm","test7.asm")
print("test 7 done")
compile_scheme_file("../debugger/scheme code to test compiler/test8.scm","test8.asm")
print("test 8 done")
compile_scheme_file("../debugger/scheme code to test compiler/test9.scm","test9.asm")
print("test 9 done")
compile_scheme_file("../debugger/scheme code to test compiler/test10.scm","test10.asm")
print("test 10 done")
compile_scheme_file("../debugger/scheme code to test compiler/test11.scm","test11.asm")
print("test 11 done")
compile_scheme_file("../debugger/scheme code to test compiler/test12.scm","test12.asm")
print("test 12 done")