
L_APPEND_Applic:

	PUSH(FP);
	MOV(FP,SP);
	PUSH(R1);

    CMP(1,FPARG(1));
    JUMP_EQ(L_APPEND_1_ARGUMENT);

	MOV(R0,FPARG(2));
    CMP(R0,IMM(2));
    JUMP_EQ(L_APPEND_EMPTY_LIST_EXIT);
    MOV(R0,INDD(R0,2));

L_APPEND_LOOP:
    CMP(R0,IMM(2)); /* check if nil */
    JUMP_EQ(L_APPEND_AFTER_LOOP);
    
    MOV(R0,INDD(R0,2));
    JUMP(L_APPEND_LOOP);

L_APPEND_AFTER_LOOP:
    MOV(R1,FPARG(3));
    MOV(R0,FPARG(2));

L_APPEND_FINAL_LOOP:
    CMP(INDD(R0,2),IMM(2)); /* check if nil */
    JUMP_EQ(L_APPEND_AFTER_FINAL_LOOP);
    MOV(R0,INDD(R0,2));
    JUMP(L_APPEND_FINAL_LOOP);

L_APPEND_AFTER_FINAL_LOOP:
    MOV(INDD(R0,2),R1);
    MOV(R0,FPARG(2));
    JUMP(L_APPEND_Applic_EXIT);

L_APPEND_1_ARGUMENT:
    MOV(R0,FPARG(2));
    JUMP(L_APPEND_Applic_EXIT);

L_APPEND_EMPTY_LIST_EXIT:
    MOV(R0,FPARG(3));

L_APPEND_Applic_EXIT:
	POP(R1);
	POP(FP);
	RETURN;
