L_APPLY_APPLIC:
	PUSH(FP);
	MOV(FP,SP);

	PUSH(R1);				/* BACKUP */
	MOV(R1, IMM(0));		/* LOOP_COUNTER */

	PUSH(IMM(2)); 			/* LIST SO FAR */
	PUSH(FPARG(3)); 		/* LIST TO APPLY */
	CALL(LIST_TO_APPLY);
	DROP(2);

APPLY_LOOP:
	CMP(R0, IMM(2));		/* DONE PUSHING? */
	JUMP_EQ(APPLY_EXIT);
	PUSH(INDD(R0,1));      	/* FIRST ARG TO APPLY */
	MOV(R0,INDD(R0,2));   	/* R0 <- R0.NEXT */
	INCR(R1);
	JUMP(APPLY_LOOP);
	
APPLY_EXIT:
	PUSH(R1);				/* NUM OF ARGS */
	
	MOV(R10,FPARG(2));
	PUSH(INDD(R10, 1));     /* ENV */
	CALLA(INDD(R10, 2));   	/* PROC OF APPLIC */
	DROP(STARG(0));
	DROP(2);
	POP(R1);
	POP(FP);
	RETURN;