
L_CHECK_MAGIC:
	CMP(R0, 7109179); /* MAGIC */
	JUMP_EQ(WRITE_SOB_NIL);
	MOV(R1, IND(R0));
	CMP(R1, IMM(T_VOID));
        JUMP_NE(L_PRINT_WITH_NEW_LINE);

L_PRINT_WITHOUT_NEW_LINE:
	PUSH(R0);
        CALL(WRITE_SOB);
	DROP(1);
	JUMP(L_CHECK_MAGIC_END);

L_PRINT_WITH_NEW_LINE:
	PUSH(R0);
        CALL(WRITE_SOB);
	CALL(NEWLINE);
	DROP(1);

L_CHECK_MAGIC_END:

	RETURN;

